### ISSUE TITLE
inserting uid into Piwik is breaking the flow by opening a new session

### ISSUE THREAD

**Issue by emasters** [CCALI/CALI-Author-Viewer-5#15]
![capture20160906-1](https://cloud.githubusercontent.com/assets/741239/18291804/2b3ddb5c-7458-11e6-99d5-5962367d8ec8.PNG)
When a Lesson run launches it needs to pick up the existing Piwik session not create a new one. That means not using the `uid` as an identifier.

**Comment by emasters** [comment]
It logs my movement through the Lesson perfectly without interfering with the performance of the Lesson. When I hit exit and resume, it picks up the Piwik session I left when I started the Lesson. When I resume the Lesson it jumps back to session defined by `uid`. It's pretty cool but we need to have both sessions together for the best tracking.

**Comment by sgoshorn** [comment]
What can we add to the Piwik loader here: https://github.com/CCALI/CALI-Author-Viewer-5/blob/master/lessons/web/share/jq/lesson.php#L54
Should the setUserId not be called at all? Is there an easy way to attach user id or some way to easily connect to the user record? Maybe attach user id to custom variable 4?

**Comment by emasters** [comment]
Let's try not setting the userid at all and seeing what Piwik does on its own.

**Comment by sgoshorn** [comment]
Removed the setuserid line. Looks like the auto id now connects it all together. Can I try adding user id to custom 4? Also, the group is missing since I don't know how to extract it.

**Comment by emasters** [comment]
You can try adding userid to Custom 4. Group info is getting in there.
![capture20160906-2](https://cloud.githubusercontent.com/assets/741239/18292409/fbf75064-745a-11e6-872d-15e7662000ca.PNG)

**Comment by sgoshorn** [comment]
Added Drupal user id to custom variable 4. It shows up but only when hovering over a lesson page link. I guess the Visitor profile summary is derived from the earliest page views. Still, quite nice. Now, do we push our luck and try treating feedback as a page view too?

**Comment by emasters** [comment]
I'm all for putting the bug where ever it'll run. Closing this ticket since the issue is resolved.
