### ISSUE TITLE
Add semester info when running LessonLink

### ISSUE THREAD

**Issue by emasters** [CCALI/CALI-Author-Viewer-5#152]
Currently when running a LessonLink the viewer displays the profs name and the course title to indicate to students that they are indeed running the assigned link for their class. It would be useful to add the semester info, like `Spring 2021`, to that indicator. That would help students and teachers to versify that they are running the current set of links. 

![LessonViewerAddSemester20210325](https://user-images.githubusercontent.com/741239/112481989-f6f23a00-8d4d-11eb-9282-afa10d1dc658.PNG)

As repeat use of LessonLink increases I'm seeing more cases where the teacher accidentally sends out the wrong link because they neglected  update an email template or syllabus. This leads to confusion on the part of everybody.

**Comment by sgoshorn** [comment]
Semester should appear at the top now. It was already in the About section but folks likely ignore that part.  632b1d47efba2b3aa55d90bda64781b136778141
