### ISSUE TITLE
Time stamp test on Teacher LessonLive poll fails

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/CALI-Author-Viewer-5#23]
Only when teacher answers a question (forcing a scoresave) does the current page report populate. The no-op time stamp check is saying there's no new data when there actually is. Time stamp behavior is off somehow.

**Comment by emasters** [comment]
@sgoshorn I can confirm that the timezone setting in Drupal is affecting the scoredate. I didn't realize that this would happen. And it gets pretty bad because if I run a Lesson, save and exit, edit my timezone in Drupal then resume the Lesson, the scordate gets set to before the rundate. That's bad. 
I'm going to try resetting the tz to the local system before the Lesson module saves any times.

**Comment by emasters** [comment]
Added
` // force the time zone back to ET. 
    date_default_timezone_set('America/New_York');`
to the Lesson module in Drupal and this overrode the Druapl TZ setting. 
The code is in place on d7.calidev for further testing.

**Comment by sgoshorn** [comment]
Is it possible the original time zone is used in Drupal code after the lesson module function are run? Should we preserve the current time zone and restore it afterwards just in case? Also, I believe there's an option to specifically call date() with a temporary time zone argument that wouldn't affect the default. Do we have the right version of PHP for that option?

**Comment by emasters** [comment]
Yes it's likely that the TZ would need to be reset before returning to Drupal, though I'm not sure what the scope of `date_default_timezone_set` is.
I don't see the option for setting a temp TZ in `date()` in the docs at http://php.net/manual/en/function.date.php. There is an option for display the TZ but not setting it. Am I missing it?

**Comment by sgoshorn** [comment]
You're right. I misread option `e` It's display only. Even option `c` wouldn't work well for our purposes. That format is hard to read. Maybe you can use `date_default_timezone_get()` to grab the current TZ in a temp variable and set it back after the date() call?

**Comment by emasters** [comment]
Seems like the scope of `date_default_timezone_set` is limited in this case to the function `cali_lessons_scoresave()`. You can see this by setting the user timezone to something other than the default (I like Phoenix) and running a LEsson. When you look at the db record for the run you'll see that the rundate is in the user's TZ but the scoredate is in ET. This happens with any number of runs. That indicates that Drupal is actively enforcing the user's TZ if it is set.

**Comment by emasters** [comment]
Just to be on the safe side I'll use `date_default_timezone_get` to grab the current TZ and then put it back when I'm done.

**Comment by sgoshorn** [comment]
This is working correctly on d7.calidev.org.
