### ISSUE TITLE
List of user lessonruns does not indicate whether they are LessonLink runs or not

### ISSUE THREAD

**Issue by johnmayer** [CCALI/CALI-Author-Viewer-5#54]
![image](https://user-images.githubusercontent.com/2457935/37794513-b3c7f682-2ddf-11e8-89d6-98201e06ae7f.png)

In the image, the lesson runs for the user for Parol Evidence Rule link the CALI website lesson - NOT the lessonlinked lesson that created those lessonruns.  This is a bug.

**Comment by emasters** [comment]
@johnmayer Please move this to the issue queue at https://github.com/CCALI/drupal7-cali
