### ISSUE TITLE
Add % answered and % total correct columns to lessonlink report and CSV download

### ISSUE THREAD

**Issue by johnmayer** [CCALI/CALI-Author-Viewer-5#55]
![image](https://user-images.githubusercontent.com/2457935/37795101-776fa804-2de1-11e8-918d-5dc726ebdc29.png)

Add two new columns to the lessonlink reports - % total correct which is based on the total number of questions in the entire lesson and % answered which is also based on the total number of questions in the lesson.  This gives the faculty member quick view into whether the students completed the entire lesson or not or enough to have completed the assignment.  This is especially an issue in classes with 20-75 students.

**Comment by emasters** [comment]
@johnmayer please move to https://github.com/CCALI/drupal7-cali
