### ISSUE TITLE
Every column header needs a tooltip or FAQ or something to explain it

### ISSUE THREAD

**Issue by johnmayer** [CCALI/CALI-Author-Viewer-5#56]
![image](https://user-images.githubusercontent.com/2457935/37795305-21e7d536-2de2-11e8-8a40-02a02403e579.png)

Date - this is EASTERN TIME
Saved Score - this is based only on the questions actually visited and answered
etc.

**Comment by emasters** [comment]
@johnmayer Please move to https://github.com/CCALI/drupal7-cali
