### ISSUE TITLE
Skip the TOC when hitting next from About page

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/CALI-Author-Viewer-5#85]
Student comment from Jennifer 8/28/2018 22:21:57: "When first clicking the lesson we are directed to the "About this Lesson," once we hit next we are brought to a blank screen on the right-hand side and on the left- hand side a table of contents it shouldn't be that way. When I click next it should start the lesson and not bring up this unnecessary page. "
SJG: We could do this. Might make even more sense to start on the first page of the lesson rather than the About since it's kind of redundant - they just read the lesson description before hitting 'Run' button.  What do you think @dquentel ?

**Comment by dquentel** [comment]
I think that if they are following a LessonLink they should see the About this Book page first. Especially if it's one of the 20% of lessons with LOs. If coming from the website, you're right @sgoshorn, they would have read it already.
