### ISSUE TITLE
TOC completion indicators

### ISSUE THREAD

**Issue by sgoshorn** [CCALI/CALI-Author-Viewer-5#97]
The subtle gray after completing a subtopic is too subtle. Add a checkmark?

**Comment by dquentel** [comment]
I like the idea of checkmark next to completed TOC categories over subtle gray. Would you have to complete all of menu heading to get the checkmark? What about sub-headings? Would checkmark appear next to it rather than main heading? That seems logical to me.

**Comment by sgoshorn** [comment]
Change the gradient on the TOC headings to a solid gray. Should increase visibility for majority of TOC headings which are usually very short length.

**Comment by sgoshorn** [comment]
682095f19c8b4e44c91efc8c92ffd2d59612c953
